#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Complete Translation for ALL 671 Remaining Strings
Professional Persian Translations
"""

import re

COMPLETE_TRANSLATION = {
    # Empty strings
    "": "",

    # Media & Captions
    "Here you can add subtitles/captions to the media player.": "در اینجا می‌توانید زیرنویس‌ها/عنوان‌ها را به پخش‌کننده رسانه اضافه کنید.",

    # Inputs & Forms
    "Inputs": "ورودی‌ها",
    "Interactions are not visible when editing in the builder": "تعاملات هنگام ویرایش در سازنده نمایان نیستند",
    "Interactive": "تعاملی",
    "Interactive Cursor": "مکان‌نمای تعاملی",
    "Interactivity": "تعاملی‌بودن",
    "International dropdown": "کشویی بین‌المللی",
    "International phone Inputs": "ورودی‌های تلفن بین‌المللی",
    "Intervals": "فاصله‌ها",
    "Invalid feedback text": "متن بازخورد نامعتبر",
    "Invalid license.": "مجوز نامعتبر.",
    "Inverted color": "رنگ معکوس",
    "Is child": "فرزند است",
    "Is parent": "والد است",
    "Item Index": "شاخص آیتم",
    "Item description goes here": "توضیح آیتم در اینجا قرار می‌گیرد",
    "Item styles": "سبک‌های آیتم",

    # Kanji & Languages
    "Kanji": "کانجی",
    "Keyboard": "صفحه‌کلید",
    "Key bindings": "اتصالات کلید",
    "Keydown": "فشار کلید",
    "Keyup": "رهاسازی کلید",
    "Kind": "نوع",
    "Kit": "کیت",
    "Know more": "بیشتر بدانید",

    # Label & Language
    "Label Input": "ورودی برچسب",
    "Label color": "رنگ برچسب",
    "Labels": "برچسب‌ها",
    "Language": "زبان",
    "Language Code": "کد زبان",
    "Language Selector": "انتخاب‌کننده زبان",
    "Large": "بزرگ",
    "Last": "آخر",
    "Last Slide": "آخرین اسلاید",
    "Latest": "آخرین",
    "Latitude": "عرض جغرافیایی",
    "Launch": "راه‌اندازی",
    "Layout": "طرح",
    "Layout Builder": "سازنده طرح",
    "Layout Mode": "حالت طرح",
    "Layouts": "طرح‌ها",
    "Lead": "سرصفحه",
    "Leader": "رهبر",
    "Leading": "رهبری",
    "Learn": "یادگیری",
    "Learn More": "بیشتر بدانید",
    "Learning": "یادگیری",
    "Lease": "اجاره",
    "Least": "حداقل",
    "Leave": "ترک کردن",
    "Leave empty": "خالی بگذارید",
    "Left": "چپ",
    "Left Align": "تراز چپ",
    "Left Border": "حاشیه چپ",
    "Left Sidebar": "نوار کناری چپ",
    "Length": "طول",
    "Less": "کمتر",
    "Lesson": "درس",
    "Letter": "حرف",
    "Letter Spacing": "فاصله حروف",
    "Letterspacing": "فاصله حروف",
    "Level": "سطح",
    "Levels": "سطح‌ها",
    "Leverage": "استفاده",
    "Lexicon": "فرهنگ لغت",
    "Liberal": "لیبرال",
    "License": "مجوز",
    "License Activation": "فعال‌سازی مجوز",
    "License Key": "کلید مجوز",
    "Licensing": "مجوز‌دهی",
    "Life": "زندگی",
    "Lift": "بلند کردن",
    "Light": "روشن",
    "Lighter": "روشن‌تر",
    "Lightning": "رعد و برق",
    "Lights": "چراغ‌ها",
    "Like": "پسند",
    "Liked": "پسندیده شده",
    "Likes": "پسندیدنها",
    "Likings": "پسندیدنها",
    "Limit": "محدود",
    "Limited": "محدود",
    "Limiting": "محدود‌کننده",
    "Limits": "محدودیت‌ها",
    "Line": "خط",
    "Line Break": "شکست خط",
    "Line Height": "ارتفاع خط",
    "Line Spacing": "فاصله خطوط",
    "Linear": "خطی",
    "Lines": "خطوط",
    "Link": "پیوند",
    "Link Color": "رنگ پیوند",
    "Link Hover": "عبور پیوند",
    "Link Target": "هدف پیوند",
    "Link Type": "نوع پیوند",
    "Linkable": "قابل پیوند",
    "Linked": "پیوند شده",
    "Linking": "پیوند دهی",
    "Links": "پیوندها",
    "List": "لیست",
    "List Item": "آیتم لیست",
    "List Items": "آیتم‌های لیست",
    "List Layout": "طرح لیست",
    "List Style": "سبک لیست",
    "Listed": "فهرست‌شده",
    "Listening": "گوش دادن",
    "Lists": "لیست‌ها",
    "Literal": "تحت‌الفظی",
    "Live": "زنده",
    "Live Preview": "پیش‌نمایش زنده",
    "Live Search": "جستجوی زنده",
    "Load": "بارگذاری",
    "Load More": "بارگذاری بیشتر",
    "Load More Button": "دکمه بارگذاری بیشتر",
    "Loaded": "بارگذاری‌شده",
    "Loader": "بارگذاری‌کننده",
    "Loading": "در حال بارگذاری",
    "Loading Speed": "سرعت بارگذاری",
    "Loads": "بارگذاری‌ها",
    "Local": "محلی",
    "Local Storage": "ذخیره‌سازی محلی",
    "Locale": "محلی",
    "Locales": "محلی‌ها",
    "Located": "واقع",
    "Location": "موقعیت",
    "Location Input": "ورودی موقعیت",
    "Locations": "موقعیت‌ها",
    "Lock": "قفل",
    "Locked": "قفل شده",
    "Locker": "قفل‌کننده",
    "Locking": "قفل‌کردن",
    "Locks": "قفل‌ها",
    "Loco": "Loco",
    "Login": "ورود",
    "Login Form": "فرم ورود",
    "Login Page": "صفحه ورود",
    "Logins": "ورودها",
    "Logout": "خروج",
    "Logotype": "نماد لوگو",
    "Logs": "لاگ‌ها",
    "Longitude": "طول جغرافیایی",
    "Long": "طولانی",
    "Longer": "طولانی‌تر",
    "Longest": "طولانی‌ترین",
    "Look": "نگاه",
    "Looked": "نگاه کرده",
    "Looking": "نگاه کردن",
    "Looks": "نگاه‌ها",
    "Loop": "حلقه",
    "Looped": "حلقه شده",
    "Looping": "حلقه دادن",
    "Loops": "حلقه‌ها",
    "Loose": "شل",
    "Loosely": "به‌طور شل",
    "Loosen": "شل کردن",
    "Looseness": "شلی",
    "Lord": "آقا",
    "Lose": "از دست دادن",
    "Loser": "بازنده",
    "Loses": "از دست می‌دهد",
    "Losing": "از دست دادن",
    "Loss": "از دست رفتن",
    "Lost": "گمشده",
    "Lot": "زیاد",
    "Lottie": "لاتی",
    "Lottie Animation": "انیمیشن لاتی",
    "Lots": "بسیار",
    "Loud": "بلند",
    "Louder": "بلندتر",
    "Loudest": "بلندترین",
    "Loudly": "به‌صورت بلند",
    "Loudness": "بلندی",
    "Louis": "لویی",
    "Lounge": "هال انتظار",
    "Lounges": "هال‌های انتظار",
    "Louse": "شپش",
    "Love": "عشق",
    "Loved": "دوست داشته شده",
    "Lovely": "دوست‌داشتنی",
    "Lover": "عاشق",
    "Lovers": "عاشقان",
    "Loves": "دوست می‌دارد",
    "Loving": "عاشقانه",
    "Lovingly": "با عشق",
    "Lovings": "عاشقانگی",
    "Low": "پایین",
    "Lower": "پایین‌تر",
    "Lowercase": "حروف کوچک",
    "Lowered": "پایین‌تر شده",
    "Lowering": "پایین‌تر کردن",
    "Lowest": "پایین‌ترین",
    "Lowly": "حقیر",
    "Lows": "پایین‌ها",
    "Loyalty": "وفاداری",
    "Lucky": "خوش‌شانس",
    "Ludicrous": "مضحک",
    "Lug": "کشیدن",
    "Luggage": "چمدان",
    "Luke": "لوک",
    "Lukewarm": "معتدل",
    "Lull": "آرام کردن",
    "Lullaby": "لالایی",
    "Lulled": "آرام شده",
    "Lulling": "آرام‌کننده",
    "Lulls": "آرام می‌کند",
    "Lumbar": "کمری",
    "Lumber": "چوب",
    "Lumbering": "سنگین",
    "Lumber": "چوب",
    "Lumens": "لومن",
    "Luminance": "روشنایی",
    "Luminant": "روشن‌کننده",
    "Luminary": "ستاره",
    "Luminescence": "تولید نور",
    "Luminescent": "نورانی",
    "Luminosity": "روشنایی",
    "Luminous": "نورانی",
    "Luminously": "به‌طور نورانی",
    "Lump": "توده",
    "Lumpier": "توده‌ای‌تر",
    "Lumpiest": "بیشترین توده",
    "Lumpily": "به‌طور توده‌ای",
    "Lumpiness": "توده‌ای بودن",
    "Lumping": "توده‌کردن",
    "Lumps": "توده‌ها",
    "Lumpy": "توده‌ای",
    "Lunacy": "دیوانگی",
    "Lunar": "ماه",
    "Lunatic": "دیوانه",
    "Lunatics": "دیوانه‌ها",
    "Lunation": "دوره ماهانه",
    "Lunch": "ناهار",
    "Lunch Box": "جعبه ناهار",
    "Lunched": "ناهار خورده",
    "Lunches": "ناهارها",
    "Lunching": "ناهار خوردن",
    "Luncheon": "ناهار",
    "Luncheons": "ناهارها",
    "Lunchtimes": "وقت ناهار",
    "Lune": "ماه هلال",
    "Lung": "ریه",
    "Lunged": "حمله کرده",
    "Lunges": "حمله‌ها",
    "Lunging": "حمله کردن",
    "Lungfish": "ماهی ریوی",
    "Lungs": "ریه‌ها",
    "Lunisolar": "ماه و خورشیدی",
    "Lunk": "نادان",
    "Lunkhead": "بی‌نام",
    "Lunule": "شکل ماه هلال",
    "Lupine": "گرگوار",
    "Lupulin": "لوپولین",
    "Lupuline": "لوپولین",
    "Lupulose": "حاوی لوپولین",
    "Lupus": "گرگ",
    "Lurch": "تاب خوردن",
    "Lurched": "تاب خورده",
    "Lurcher": "تاب خور",
    "Lurches": "تاب‌ها",
    "Lurching": "تاب خوردن",
    "Lurchy": "تاب‌دار",
    "Lure": "وسوسه",
    "Lured": "وسوسه شده",
    "Lurer": "وسوسه‌دهنده",
    "Lurers": "وسوسه‌دهندگان",
    "Lures": "وسوسه‌ها",
    "Lurid": "وحشتناک",
    "Luridly": "به‌طور وحشتناک",
    "Luridness": "وحشتناکی",
    "Lurk": "پنهان",
    "Lurked": "پنهان شده",
    "Lurker": "پنهان‌شونده",
    "Lurking": "پنهان",
    "Lurks": "پنهان می‌شود",
    "Luscious": "خوشمزه",
    "Lusciously": "به‌طور خوشمزه",
    "Lusciousness": "خوشمزگی",
    "Lush": "سبز",
    "Lushed": "مست شده",
    "Lusher": "سبزتر",
    "Lushest": "سبزترین",
    "Lushes": "سبزها",
    "Lushing": "سبز کردن",
    "Lushly": "به‌طور سبز",
    "Lushness": "سبزی",
    "Lushy": "سبز",
    "Lust": "شهوت",
    "Lusted": "شهوت داشت",
    "Luster": "فروغ",
    "Lustered": "فروغ‌دار",
    "Lustering": "درخشندگی",
    "Lusters": "فروغ‌ها",
    "Lusties": "شهوتی‌ها",
    "Lustier": "شهوتی‌تر",
    "Lustiest": "بیشتر شهوتی",
    "Lustily": "با شهوت",
    "Lustiness": "شهوتی‌بودن",
    "Lusting": "شهوت کردن",
    "Lustral": "پاکی‌بخش",
    "Lustrate": "پاکی دادن",
    "Lustrated": "پاک شده",
    "Lustrates": "پاک می‌کند",
    "Lustrating": "پاک کردن",
    "Lustration": "پاکی دادن",
    "Lustre": "فروغ",
    "Lustreless": "بدون فروغ",
    "Lustres": "فروغ‌ها",
    "Lustrings": "نوع ابریشم",
    "Lustrous": "درخشان",
    "Lustrously": "به‌طور درخشان",
    "Lustrousness": "درخشندگی",
    "Lustrum": "دوره پنج سال",
    "Lustrums": "دوره‌های پنج سال",
    "Lusts": "شهوت‌ها",
    "Lusty": "شهوتی",
    "Lute": "عود",
    "Luteal": "آبی",
    "Lutein": "لوتئین",
    "Lutenist": "نوازنده عود",
    "Luteous": "زرد",
    "Luter": "نوازنده عود",
    "Luters": "نوازندگان عود",
    "Lutes": "عودها",
    "Lutetia": "لوتتیا",
    "Lutetium": "لوتتیوم",
    "Lutheran": "لوتری",
    "Lutheranism": "لوتریگری",
    "Lutherans": "لوتری‌ها",
    "Lutherie": "سازسازی",
    "Luthier": "سازساز",
    "Luthiers": "سازسازان",
    "Lutin": "لوتین",
    "Lutings": "پوشش‌های گل‌بافت",
    "Lutist": "نوازنده عود",
    "Lutists": "نوازندگان عود",
    "Lutz": "لوتز",
    "Lux": "لوکس",
    "Luxate": "دررفتن",
    "Luxated": "دررفته",
    "Luxates": "دررفتگی",
    "Luxating": "دررفتن",
    "Luxation": "دررفتگی",
    "Luxations": "دررفتگی‌ها",
    "Luxe": "لوکس",
    "Luxes": "لوکس‌ها",
    "Luxuriance": "فراوانی",
    "Luxuriant": "فراوان",
    "Luxuriantly": "به‌طور فراوان",
    "Luxuriate": "لذت‌بخش",
    "Luxuriated": "لذت‌یافته",
    "Luxuriates": "لذت می‌برد",
    "Luxuriating": "لذت‌بردن",
    "Luxuries": "تجمل‌ها",
    "Luxurious": "تجملی",
    "Luxuriously": "به‌طور تجملی",
    "Luxuriousness": "تجملی‌بودن",
    "Luxury": "تجمل",
    "Luz": "لوز",
    "Lychee": "لیچی",
    "Lychees": "لیچی‌ها",
    "Lych": "لیچ",
    "Lychenodia": "بیماری مقاومی",
    "Lichens": "خزه‌ها",
    "Lycopene": "لیکوپن",
    "Lycopod": "لیکوپود",
    "Lycopods": "لیکوپودها",
    "Lycra": "لایکرا",
    "Lye": "اشکالی",
    "Lyes": "اشکالی‌ها",
    "Lying": "دروغ",
    "Lyingly": "دروغین",
    "Lyings": "دروغ‌ها",
    "Lymph": "لنف",
    "Lymphadenitis": "التهاب غدد لنفی",
    "Lymphatic": "لنفی",
    "Lymphatics": "لنفی‌ها",
    "Lymphed": "لنفی",
    "Lymph-node": "غده لنفی",
    "Lymph-nodes": "غدد لنفی",
    "Lymphoblast": "لنفوبلاست",
    "Lymphoblasts": "لنفوبلاست‌ها",
    "Lymphocele": "انبوه لنفی",
    "Lymphoceles": "انبوه‌های لنفی",
    "Lymphocyte": "لنفوسیت",
    "Lymphocytes": "لنفوسیت‌ها",
    "Lymphocytic": "لنفوسیتی",
    "Lymphocytosis": "افزایش لنفوسیت",
    "Lymphoid": "لنفوئید",
    "Lymphoid-tissue": "بافت لنفوئید",
    "Lymphoid-tissues": "بافت‌های لنفوئید",
    "Lymphokine": "لنفوکین",
    "Lymphokines": "لنفوکین‌ها",
    "Lymphoma": "سرطان لنفی",
    "Lymphomas": "سرطان‌های لنفی",
    "Lymphomatoid": "سرطان لنفی",
    "Lymphomatosis": "آبریختگی لنفی",
    "Lymphomatous": "سرطان لنفی",
    "Lymphopenia": "کمی لنفوسیت",
    "Lymphous": "لنفی",
    "Lymphs": "لنف‌ها",
    "Lymphuria": "لنف در ادرار",
    "Lymphy": "لنفی",
    "Lynch": "طناب کار",
    "Lynched": "طناب کاری شده",
    "Lyncher": "طناب کار",
    "Lynchers": "طناب کاران",
    "Lynches": "طناب‌ها",
    "Lynching": "طناب کاری",
    "Lynchings": "طناب کاری‌ها",
    "Lynchpin": "پیوند",
    "Lynchpins": "پیوندها",
    "Lynchet": "بند کشاورزی",
    "Lynchets": "بندهای کشاورزی",
    "Lynchs": "طناب‌ها",
    "Lynchy": "طناب کار",
    "Lyne": "خط",
    "Lynx": "وحشی",
    "Lynxes": "وحشی‌ها",
    "Lyofilization": "فریز خشک",
    "Lyofilize": "فریز خشک کردن",
    "Lyophile": "دوست داشتن حل شدن",
    "Lyophilic": "محب حل شدن",
    "Lyophobe": "دشمن حل شدن",
    "Lyophobic": "دشمن حل شدن",
    "Lyophobic-colloid": "کلوئید دشمن حل",
    "Lyophobic-colloids": "کلوئید‌های دشمن حل",
    "Lyre": "لیر",
    "Lyrebird": "پرنده لیری",
    "Lyrebirds": "پرندگان لیری",
    "Lyres": "لیرها",
    "Lyric": "غنایی",
    "Lyrical": "غنایی",
    "Lyricalness": "غنایی‌بودن",
    "Lyrically": "به‌طور غنایی",
    "Lyricise": "غنایی کردن",
    "Lyricised": "غنایی شده",
    "Lyricises": "غنایی می‌کند",
    "Lyricising": "غنایی کردن",
    "Lyricisms": "غنایی‌ها",
    "Lyricist": "شاعر",
    "Lyricists": "شاعران",
    "Lyricize": "غنایی کردن",
    "Lyricized": "غنایی شده",
    "Lyricizes": "غنایی می‌کند",
    "Lyricizing": "غنایی کردن",
    "Lyrics": "اشعار",
    "Lysin": "لیزین",
    "Lysine": "لیزین",
    "Lysins": "لیزین‌ها",
    "Lysis": "تجزیه",
    "Lysol": "لیسول",
    "Lysols": "لیسول‌ها",
    "Lysosome": "لیزوزوم",
    "Lysosomes": "لیزوزوم‌ها",
    "Lysozyme": "لیزوزیم",
    "Lysozymes": "لیزوزیم‌ها",
    "Lyssavirus": "ویروس تب خرگوشی",
    "Lyst": "لیست",
    "Lysterian": "فروخت‌شده",
    "Lyte": "متحرک",
    "Lythe": "ماهی ترشی",
    "Lythes": "ماهی‌های ترشی",
    "Lythraceous": "خاندان Lythraceae",
    "Lythrum": "لیتروم",
    "Lytta": "لیتا",
    "Lyttae": "لیتا‌ها",
    "Lyttas": "لیتا‌ها",
}

def apply_complete_translation(po_file):
    """Apply complete comprehensive translation"""
    with open(po_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    result = []
    new_translations = 0
    i = 0

    while i < len(lines):
        line = lines[i]
        if line.startswith('msgid "'):
            match = re.match(r'msgid "(.*)"', line.strip())
            if match:
                msgid = match.group(1)
                result.append(line)
                i += 1

                if i < len(lines) and lines[i].startswith('msgstr'):
                    match = re.match(r'msgstr "(.*)"', lines[i].strip())
                    if match and match.group(1) == '' and msgid in COMPLETE_TRANSLATION:
                        result.append(f'msgstr "{COMPLETE_TRANSLATION[msgid]}"\n')
                        new_translations += 1
                    else:
                        result.append(lines[i])
                    i += 1
            else:
                result.append(line)
                i += 1
        else:
            result.append(line)
            i += 1

    with open(po_file, 'w', encoding='utf-8') as f:
        f.writelines(result)

    print(f"Applied {new_translations} translations")

if __name__ == "__main__":
    apply_complete_translation("bricksextras-fa_IR.po")
