#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import sys

# Persian translations dictionary
translations = {
    "%s Conditions": "%s شرایط",
    "(touch devices)": "(دستگاه های لمسی)",
    "1 month": "1 ماه",
    "1 year": "1 سال",
    "A slide height must be set for this to apply": "برای اعمال این گزینه باید ارتفاع اسلاید تنظیم شود",
    "A slider height or aspect-ratio must be set for vertical sliders": "برای اسلایدرهای عمودی باید ارتفاع یا نسبت ابعاد تنظیم شود",
    "A-Z index": "نمایه الفبایی",
    "API keys": "کلیدهای API",
    "Above": "بالا",
    "Accessibility": "دسترسی‌پذیری",
    "Accordion Item": "آیتم آکوردئون",
    "Accordion Item Index": "شاخص آیتم آکوردئون",
    "Accordion Toggle": "تغییر وضعیت آکوردئون",
    "Accordion collapse": "بستن آکوردئون",
    "Accordion expand": "بازکردن آکوردئون",
    "Accordion header": "سربرگ آکوردئون",
    "Accuracy": "دقت",
    "Activate License": "فعال‌سازی مجوز",
    "Adapt slider height to current slide height": "تطبیق ارتفاع اسلایدر با ارتفاع اسلاید فعلی",
    "Adaptive height at this breakpoint": "ارتفاع تطبیقی در این نقطه شکست",
    "Add %s to trigger": "اضافه کردن %s به فعال‌کننده",
    "Add Markers": "اضافه کردن نشانگرها",
    "Add chapters with query loop": "افزودن فصل‌ها با حلقه پرسش",
    "Add form ID dynamically": "افزودن شناسه فرم به صورت پویا",
    "Add glare": "افزودن درخشندگی",
    "Add item to favorite": "اضافه کردن آیتم به علاقه‌مندی‌ها",
    "Add loop fade effect": "اضافه کردن اثر محو حلقه",
    "Add rows & cells manually": "اضافه کردن سطرها و سلول‌ها به صورت دستی",
    "Add rows and cells. The number of visible rows depends on pagination settings.": "سطرها و سلول‌ها را اضافه کنید. تعداد سطرهای نمایان به تنظیمات صفحه‌بندی بستگی دارد.",
    "Add the required number of columns": "تعداد ستون‌های مورد نیاز را اضافه کنید",
    "Add to favorites": "اضافه کردن به علاقه‌مندی‌ها",
    "Added to favorite": "به علاقه‌مندی افزوده شد",
    "Added to favorites": "به علاقه‌مندی‌ها افزوده شد",
    "Added to list": "به لیست افزوده شد",
    "Adjacent Post": "نوشته مجاور",
    "Adjacent Post Order": "ترتیب نوشته مجاور",
    "Adjacent Posts": "نوشته‌های مجاور",
    "After": "بعد",
    "After dismissal, show again after:": "پس از رفع، دوباره نمایش دهید بعد از:",
    "After first play": "بعد از اولین پخش",
    "Alert closed": "هشدار بسته شد",
    "Alert shown": "هشدار نمایش داده شد",
    "All Items": "تمام آیتم‌ها",
    "All items cleared": "تمام آیتم‌ها پاک شدند",
    "All users": "تمام کاربران",
    "All-Day Event?": "رویداد تمام روز؟",
    "All-Day Text": "متن تمام روز",
    "Allow ID styling to be added": "اجازه دهید سبک‌سازی شناسه اضافه شود",
    "Allow action while player is fullscreen": "اجازه اقدام زمانی که پخش‌کننده تمام صفحه است",
    "Allow events to repeat": "اجازه تکرار رویدادها",
    "Allow keyboard navigation to inactive tabs": "اجازه ناوبری صفحه‌کلید به برگه‌های غیرفعال",
    "Allow multiple sources": "اجازه دهید منابع متعدد",
    "Allow target element to be clicked": "اجازه کلیک بر روی عنصر هدف",
    "Alphanumeric": "الفبای‌عددی",
    "Alternating layout": "طرح بندی متناوب",
    "Always closed on page load": "همیشه بسته شده در بارگذاری صفحه",
    "An error occurred, please try again.": "خطایی رخ داده است، لطفاً دوباره سعی کنید.",
    "Anchor": "لنگر",
    "Animated checkmark": "علامت تیک متحرک",
    "Animation scale": "مقیاس انیمیشن",
    "Animation translate Y": "ترجمه Y انیمیشن",
    "Announcements": "اعلان‌ها",
    "Announcer": "گوینده",
    "Any status": "هر وضعیتی",
    "Append to body": "اضافه کردن به بدنه",
    "Archive type": "نوع بایگانی",
    "Are you sure you want to exit the tour?": "آیا مطمئن هستید که می‌خواهید از تور خارج شوید؟",
    "Aria Labels": "برچسب‌های Aria",
    "Aria label": "برچسب Aria",
    "Arrow": "فلش",
    "Arrow Key Navigation": "ناوبری با کلیدهای فلش",
    "Artist": "هنرمند",
    "Aspect Ratio": "نسبت ابعاد",
    "Assertive - Interrupt to announce immediately": "تاکیدی - وقفه برای اعلام فوری",
    "Asterisk": "ستاره‌ای",
    "At least 1 entry exists": "حداقل 1 ورودی وجود دارد",
    "At least one search result": "حداقل یک نتیجه جستجو",
    "Attachment Alt Text": "متن جایگزین پیوست",
    "Attachment Caption": "عنوان پیوست",
    "Attachment Description": "توضیحات پیوست",
    "Attachment File URL": "URL فایل پیوست",
    "Attachment Title": "عنوان پیوست",
    "Audio": "صوتی",
    "Author archive": "بایگانی نویسنده",
    "Author has CPT entry": "نویسنده دارای ورودی CPT است",
    "Authored by logged in user": "نوشته شده توسط کاربر وارد شده",
    "Authored by logged-in user": "نوشته شده توسط کاربر وارد شده",
    "Auto": "خودکار",
    "Auto End": "پایان خودکار",
    "Auto Start": "شروع خودکار",
    "Auto pause": "توقف خودکار",
    "Auto rotate speed": "سرعت چرخش خودکار",
    "Auto scroll": "لغزش خودکار",
    "Auto-detect language": "تشخیص خودکار زبان",
    "Auto-enable captions": "فعال‌سازی خودکار زیرنویس",
    "Auto-resume on page load": "ادامه خودکار در بارگذاری صفحه",
    "Automatically add unique IDs to headings": "اضافه کردن خودکار شناسه‌های منحصر به فرد به سرفصل‌ها",
    "Automatically hide custom buttons": "پنهان کردن خودکار دکمه‌های سفارشی",
    "Automatically open keyboard when search opens": "باز کردن خودکار صفحه‌کلید هنگام باز شدن جستجو",
    "Automatically select captions matching site language": "انتخاب خودکار زیرنویس‌های منطبق با زبان سایت",
    "Autoplay progress": "پیشرفت پخش خودکار",
    "Autoplay video": "پخش خودکار ویدیو",
    "Autoplay when modal reopens": "پخش خودکار هنگام بازگشایی مودال",
    "Axes": "محورها",
    "Back": "بازگشت",
    "Back to Top": "بازگشت به بالا",
    "Backdrop": "پس‌زمینه",
    "Background Event Color": "رنگ رویداد پس‌زمینه",
    "Background Event Opacity": "کدری رویداد پس‌زمینه",
    "Background color": "رنگ پس‌زمینه",
    "Before": "قبل",
    "Before / After Image": "تصویر قبل / بعد",
    "Before first play": "قبل از اولین پخش",
    "Before ready to play": "قبل از آمادگی برای پخش",
    "Begin At Zero": "شروع در صفر",
    "Behavior": "رفتار",
    "Below": "پایین",
    "Below header": "زیر سرصفحه",
    "Block": "مسدود کردن",
    "Body classes": "کلاس‌های بدنه",
    "Border": "حاشیه",
    "Border radius": "شعاع حاشیه",
    "Bottom Center": "پایین مرکز",
    "Bottom End": "پایان پایین",
    "Bottom Left": "پایین چپ",
    "Bottom Right": "پایین راست",
    "Bottom Start": "شروع پایین",
    "Bottom controls": "کنترل‌های پایین",
    "Bottom of viewport": "پایین دید‌پنجره",
    "Box shadow": "سایه جعبه",
    "Breadcrumb links": "پیوندهای ردپای نان",
    "Breadcrumbs source": "منبع ردپای نان",
    "Bricks Lazy load": "بارگذاری تنبل Bricks",
    "Buffered": "ذخیره‌سازی موقت",
    "Built-in Hotspots": "نقاط داغ تعبیه‌شده",
    "Burger Trigger": "فعال‌کننده منو",
    "Burger line border radius": "شعاع حاشیه خط منو",
    "Button Active Background": "پس‌زمینه دکمه فعال",
    "Button Active Border": "حاشیه دکمه فعال",
    "Button Background": "پس‌زمینه دکمه",
    "Button Border": "حاشیه دکمه",
    "Button Hover Background": "پس‌زمینه عبور دکمه",
    "Button Hover Border": "حاشیه عبور دکمه",
    "Button Text": "متن دکمه",
    "Button reset": "بازنشانی دکمه",
    "Buttons": "دکمه‌ها",
    "By Day of Month": "بر اساس روز ماه",
    "By Day of Week": "بر اساس روز هفته",
    "By Day of Year": "بر اساس روز سال",
    "By Hour": "بر اساس ساعت",
    "By Minute": "بر اساس دقیقه",
    "By Month": "بر اساس ماه",
    "By Position": "بر اساس موقعیت",
    "By Second": "بر اساس ثانیه",
    "By Week Number": "بر اساس شماره هفته",
    "Bypass internal caching": "دور زدن نهادن داخلی",
    "Byte": "بایت",
    "CDN Token Key": "کلید توکن CDN",
    "CPT has at least 1 published entry": "CPT حداقل 1 ورودی منتشر شده دارد",
    "Calendar": "تقویم",
    "Calendar UI": "رابط کاربری تقویم",
    "Can be swiped away": "می‌تواند لغزانده شود",
    "Cancelled": "لغو شده",
    "Caption Cues": "نشانه‌های زیرنویس",
    "Caption Settings": "تنظیمات زیرنویس",
    "Caption toggle": "تغییر وضعیت زیرنویس",
    "Captions": "زیرنویس‌ها",
    "Captions Off": "زیرنویس‌ها خاموش",
    "Captions On": "زیرنویس‌ها روشن",
    "Cart count": "تعداد سبد",
    "Cart empty": "سبد خالی است",
    "Cart total": "جمع سبد",
    "Cart total (%s)": "جمع سبد (%s)",
    "Cart total (%s) excl. shipping": "جمع سبد (%s) بدون حمل‌ونقل",
    "Cart weight": "وزن سبد",
    "Cart weight (%s)": "وزن سبد (%s)",
    "Category archive": "بایگانی دسته‌بندی",
    "Cell": "سلول",
    "Cell content on new line": "محتوای سلول در خط جدید",
    "Cell data for this column": "داده‌های سلول برای این ستون",
    "Cell inline padding": "آمادگی درونی سلول",
    "Cells": "سلول‌ها",
    "Center": "مرکز",
    "Center controls": "کنترل‌های مرکزی",
    "Center cutout": "برش مرکزی",
    "Changelog": "تغییرات",
    "Chapter": "فصل",
    "Chapter menu items": "آیتم‌های منوی فصل",
    "Chapter title": "عنوان فصل",
    "Chapters": "فصل‌ها",
    "Chart": "نمودار",
    "Chart stacking": "انباشت نمودار",
    "Chart style": "سبک نمودار",
    "Checkable Grid": "شبکه قابل انتخاب",
    "Checkboxes, radios, range sliders, progress bars, and submit buttons.": "چک‌باکس‌ها، دکمه‌های رادیویی، لغزنده‌های محدوده، نوار پیشرفت و دکمه‌های ارسال.",
    "Checked": "انتخاب شده",
    "Child Items of Parent": "آیتم‌های فرزند والد",
    "Choose the starting layout for the player": "انتخاب طرح اولیه برای پخش‌کننده",
    "Choose which taxonomy to display for each custom post type": "انتخاب کنید کدام تاکسونومی برای هر نوع نوشته سفارشی نمایش داده شود",
    "Circumference": "محیط",
    "Classy": "شیک",
    "Classy Rounded": "شیک و گرد",
    "Clear all": "پاک کردن همه",
    "Clear button": "دکمه پاک کردن",
    "Clear progress on cancel": "پاک کردن پیشرفت در لغو",
    "Cleared": "پاک شده",
    "Click backdrop to close": "برای بستن بر روی پس‌زمینه کلیک کنید",
    "Click on another element": "بر روی عنصر دیگری کلیک کنید",
    "Click on this element": "بر روی این عنصر کلیک کنید",
    "Click overlay to exit tour": "برای خروج از تور بر روی پوشش کلیک کنید",
    "Click to play": "برای پخش کلیک کنید",
    "Clicking hashlink will close": "کلیک بر روی hashlink بسته خواهد شد",
    "Clip direction": "جهت برش",
    "Clip end": "پایان برش",
    "Clip start": "شروع برش",
    "Close Search": "بستن جستجو",
    "Close at this breakpoint": "بسته شود در این نقطه شکست",
    "Close element": "عنصر بسته",
    "Close modal": "بستن مودال",
    "Close other offcanvas": "بستن دیگر offcanvas",
    "Closed-Captions Off": "زیرنویس بسته خاموش",
    "Closed-Captions On": "زیرنویس بسته روشن",
    "Collapse depth": "عمق بستن",
    "Collapse in builder": "بستن در سازنده",
    "Collapsing": "در حال بستن",
    "Color": "رنگ",
    "Color Scheme Toggle": "تغییر وضعیت طرح رنگ",
    "Color scheme": "طرح رنگ",
    "Color scheme: %s.": "طرح رنگ: %s.",
    "Color scheme: %s. Click to toggle.": "طرح رنگ: %s. برای تغییر وضعیت کلیک کنید.",
    "Color scheme: {x_color_scheme}. Click to toggle.": "طرح رنگ: {x_color_scheme}. برای تغییر وضعیت کلیک کنید.",
    "Column count": "تعداد ستون",
    "Column heading": "سربرگ ستون",
    "Column labels": "برچسب‌های ستون",
    "Completed": "انجام شده",
    "Completed progress bars, save buttons, and success messages.": "نوار پیشرفت انجام شده، دکمه‌های ذخیره و پیام‌های موفقیت.",
    "Component scope": "دامنه جزء",
    "Conditional accordion": "آکوردئون شرطی",
    "Conditional display": "نمایش شرطی",
    "Conditional slider": "اسلایدر شرطی",
    "Conditions": "شرایط",
    "Config": "پیکربندی",
    "Configure output": "پیکربندی خروجی",
    "Configure the layout & behavior using the element ID, not a class": "پیکربندی طرح و رفتار با استفاده از شناسه عنصر، نه کلاس",
    "Confirm Cancel": "تایید لغو",
    "Confirm Cancel Message": "پیام تایید لغو",
    "Content Switcher": "تبدیل کننده محتوا",
    "Content Timeline": "خط زمانی محتوا",
    "Content block": "بلوک محتوا",
    "Content from the link will appear here (images, videos or iFrame)": "محتوای پیوند در اینجا ظاهر خواهد شد (تصاویر، ویدیوها یا iFrame)",
    "Content here": "محتوا در اینجا",
    "Content inner": "درون محتوا",
    "Content switchers to control": "تبدیل کننده‌های محتوا برای کنترل",
    "Content will appear here.": "محتوا در اینجا ظاهر خواهد شد.",
    "Content wrapper": "بسته‌بندی محتوا",
    "Context Icon": "نماد زمینه",
    "Continuous": "پیوسته",
    "Control": "کنترل",
    "Control height": "ارتفاع کنترل",
    "Control how all elements on the page switch between color modes (effect not seen inside builder)": "کنترل اینکه چگونه تمام عناصر در صفحه بین حالت‌های رنگ تبدیل شوند (اثر در سازنده دیده نمی‌شود)",
    "Control zones gap": "شکاف مناطق کنترل",
    "Copy": "کپی",
    "Copy URL": "کپی URL",
    "Copy failed": "کپی ناموفق",
    "Copy returned empty": "کپی خالی برگشت",
    "Copy success": "کپی موفق",
    "Copy to Clipboard": "کپی به حافظه موقت",
    "Corner dots": "نقاط گوشه",
    "Corner squares": "مربع‌های گوشه",
    "Corners": "گوشه‌ها",
    "Count": "شمارش",
    "Count Up": "شمارش معکوس",
    "Countdown End": "پایان شمارش معکوس",
    "Counting pages or slides": "شمارش صفحات یا اسلایدها",
    "Country": "کشور",
    "Country dial code": "کد تماس کشور",
    "Country dial code highlight": "برجسته‌سازی کد تماس کشور",
    "Country highlight": "برجسته‌سازی کشور",
    "Country list": "لیست کشورها",
    "Create expiring video URLs": "ایجاد URL‌های ویدیویی منقضی‌شونده",
    "Cumulative watch time": "زمان تماشای تجمعی",
    "Current Taxonomy Term Has Child": "اصطلاح تاکسونومی فعلی فرزندی دارد",
    "Current Taxonomy Term Has Parent": "اصطلاح تاکسونومی فعلی والدی دارد",
    "Current Taxonomy Term Is": "اصطلاح تاکسونومی فعلی است",
    "Current Taxonomy Term Is Descendant Of": "اصطلاح تاکسونومی فعلی فرزند است",
    "Current day (of month)": "روز فعلی (ماه)",
    "Current day of month": "روز فعلی از ماه",
    "Current month": "ماه فعلی",
    "Current product in cart": "محصول فعلی در سبد",
    "Current slide": "اسلاید فعلی",
    "Current slide number": "شماره اسلاید فعلی",
    "Current taxonomy term has child": "اصطلاح تاکسونومی فعلی فرزندی دارد",
    "Current taxonomy term has parent": "اصطلاح تاکسونومی فعلی والدی دارد",
    "Current taxonomy term is": "اصطلاح تاکسونومی فعلی است",
    "Current taxonomy term is descendant of": "اصطلاح تاکسونومی فعلی فرزند است",
    "Current time": "زمان فعلی",
    "Current year": "سال فعلی",
    "Cursor ball": "کره مکان‌نما",
    "Cursor position": "موقعیت مکان‌نما",
    "Cursor trail": "ردِ مکان‌نما",
    "Custom": "سفارشی",
    "Custom UI": "رابط کاربری سفارشی",
    "Custom checkbox styles": "سبک‌های چک‌باکس سفارشی",
    "Custom element": "عنصر سفارشی",
    "Custom icons": "نمادهای سفارشی",
    "Custom list": "لیست سفارشی",
    "Custom navigation using your own buttons": "ناوبری سفارشی با استفاده از دکمه‌های خود",
    "Custom post types": "انواع نوشته سفارشی",
    "Customer logout": "خروج مشتری",
    "Customize UI": "سفارشی‌سازی رابط کاربری",
    "Danger message": "پیام خطر",
    "Dark": "تاریک",
    "Dark icon": "نماد تاریک",
    "Data labels": "برچسب‌های داده",
    "Data point": "نقطه داده",
    "Data point color": "رنگ نقطه داده",
    "Data points": "نقاط داده",
    "Dataset": "مجموعه داده",
    "Dataset color": "رنگ مجموعه داده",
    "Dataset colors": "رنگ‌های مجموعه داده",
    "Datasets": "مجموعه‌های داده",
    "Date archive": "بایگانی تاریخ",
    "Date calendar": "تقویم تاریخ",
    "Date field value": "مقدار فیلد تاریخ",
    "Datetime field value": "مقدار فیلد تاریخ و زمان",
    "Day": "روز",
    "Day Button": "دکمه روز",
    "Day Grid": "شبکه روزانه",
    "Day List": "لیست روزانه",
    "Day Timeline": "خط زمانی روزانه",
    "Days": "روزها",
    "Default Tooltip Placement": "موقعیت پیش‌فرض نکته ابزار",
    "Default color": "رنگ پیش‌فرض",
    "Default color for menus": "رنگ پیش‌فرض برای منوها",
    "Defaults to featured image if not set": "به تصویر ویژه پیش‌فرض درنظر گرفته می‌شود اگر تنظیم نشده باشد",
    "Delay": "تاخیر",
    "Desktop instructions text": "متن دستورالعمل دسک‌تاپ",
    "Disable": "غیرفعال",
    "Disable Bricks animations in content": "غیرفعال کردن انیمیشن‌های Bricks در محتوا",
    "Disable Pulse on Hover": "غیرفعال کردن Pulse در هنگام عبور",
    "Disable closing sibling items": "غیرفعال کردن بستن آیتم‌های هم‌تراز",
    "Disable if adding your own buttons/links inside each step": "غیرفعال کنید اگر دکمه‌ها/پیوندهای خود را در هر مرحله اضافه می‌کنید",
    "Disable if prefer to rely on Bricks smooth scroll or another solution": "اگر ترجیح می‌دهید بر روی لغزش نرم Bricks یا راه حل دیگری متکی باشید، غیرفعال کنید",
    "Disable scroll when open": "غیرفعال کردن لغزش هنگام باز",
    "Disable slider if not enough slides to fill slider viewport": "اگر اسلایدهای کافی برای پر کردن دید‌پنجره اسلایدر وجود نداشته باشد، اسلایدر را غیرفعال کنید",
    "Disable sorting for this column": "غیرفعال کردن مرتب‌سازی برای این ستون",
    "Dismiss Button": "دکمه رفع",
    "Dismissible": "قابل رفع",
    "Display current": "نمایش فعلی",
    "Display end time for events": "نمایش زمان پایان برای رویدادها",
    "Display gesture instructions": "نمایش دستورالعمل‌های ژست",
    "Distance along the side of the button": "فاصله در طول کنار دکمه",
    "Distance along the side of the marker": "فاصله در طول کنار نشانگر",
    "Distance away from the button": "فاصله دور از دکمه",
    "Distance away from the marker": "فاصله دور از نشانگر",
    "Distance from edges": "فاصله از لبه‌ها",
    "Distance scrolled down the page before header becomes sticky": "فاصله لغزیده شده پایین صفحه قبل از اینکه سرصفحه چسبناک شود",
    "Does not have subscription": "اشتراک ندارد",
    "Dot inside radio input": "نقطه داخل ورودی رادیویی",
    "Doughnut": "دونات",
    "Download": "دانلود",
    "Download Option": "گزینه دانلود",
    "Draft": "پیش‌نویس",
    "Dropdown": "منوی کشویی",
    "Dropdown border": "حاشیه منوی کشویی",
    "Dropdown box shadow": "سایه جعبه منوی کشویی",
    "Dropdown container": "بسته‌بندی منوی کشویی",
    "Dropdown options": "گزینه‌های منوی کشویی",
    "Duration": "مدت زمان",
    "Duration of each time slot (e.g., 00:15:00 for 15 minutes)": "مدت زمان هر شکاف زمانی (به عنوان مثال، 00:15:00 برای 15 دقیقه)",
    "Dynamic Chart": "نمودار پویا",
    "Dynamic Lightbox": "جعبه نور پویا",
    "Dynamic Table": "جدول پویا",
    "Dynamic aria-label": "aria-label پویا",
    "Dynamic lightbox": "جعبه نور پویا",
    "Dynamic tooltip text": "متن نکته ابزار پویا",
    "Easing": "سهولت",
    "Element Interactions": "تعاملات عنصر",
    "Element containing the text": "عنصر حاوی متن",
    "Elements": "عناصر",
    "Elements with the data-x-modal-close attribute can close the modal": "عناصری با ویژگی data-x-modal-close می‌توانند مودال را ببندند",
    "Enable": "فعال",
    "Enable Recurring Events": "فعال‌سازی رویدادهای تکراری",
    "Enable cursor movement to control slider": "فعال‌سازی حرکت مکان‌نما برای کنترل اسلایدر",
    "Enable if your Bunny Stream has CDN Token Authentication enabled": "اگر Bunny Stream شما دارای احراز هویت توکن CDN فعال است، فعال کنید",
    "Enable tooltips": "فعال‌سازی نکات ابزار",
    "End Date/Time": "تاریخ/زمان پایان",
    "End frame": "قاب پایان",
    "End when bottom of container reaches..": "پایان زمانی که پایین بسته‌بندی به..رسد",
    "Ended": "پایان یافته",
    "Enter": "وارد",
    "Enter Fullscreen": "ورود به تمام صفحه",
    "Enter PIP": "ورود به PIP",
    "Enter a single class name": "یک نام کلاس واحد وارد کنید",
    "Enter opening and closing shortcode tags": "برچسب‌های کد کوتاه باز و بسته‌شده را وارد کنید",
    "Enter term ID": "شناسه اصطلاح را وارد کنید",
    "Enter your API key": "کلید API خود را وارد کنید",
    "Enter your CDN token key": "کلید توکن CDN خود را وارد کنید",
    "Enter your library ID": "شناسه کتاب‌خانه خود را وارد کنید",
    "Enter your license key": "کلید مجوز خود را وارد کنید",
    "Error correction": "تصحیح خطا",
    "Esc to close": "Esc برای بستن",
    "Est. year - current year": "سال تخمینی - سال فعلی",
    "Even": "زوج",
    "Event": "رویداد",
    "Event Background": "پس‌زمینه رویداد",
    "Event Border": "حاشیه رویداد",
    "Event Click Action": "عمل کلیک رویداد",
    "Event Overrides": "لغو‌های رویداد",
    "Event Selected Overlay": "پوشش انتخاب شده رویداد",
    "Event Text": "متن رویداد",
    "Event display": "نمایش رویداد",
    "Event display style": "سبک نمایش رویداد",
    "Events": "رویدادها",
    "Evergreen": "همیشه سبز",
    "Exclude Categories": "استثنا دسته‌بندی‌ها",
    "Exclude Product Categories": "استثنا دسته‌بندی‌های محصول",
    "Excluded Term IDs": "شناسه‌های اصطلاح استثنا شده",
    "Excluding shipping": "بدون حمل‌ونقل",
    "Exclusion Dates": "تاریخ‌های استثنا",
    "Exit": "خروج",
    "Exit Fullscreen": "خروج از تمام صفحه",
    "Exit PIP": "خروج از PIP",
    "Expand to show active item": "بسط برای نمایش آیتم فعال",
    "Expanding": "در حال بسط",
    "Expired": "منقضی شده",
    "Extra Rounded": "بسیار گرد",
    "Extras": "اضافات",
    "Facet Styler": "سبک‌سازی رویه",
    "Fade": "محو",
    "Failed": "ناموفق",
    "False": "نادرست",
    "Favorite Button": "دکمه علاقه",
    "Favorite Count": "تعداد علاقه",
    "Favorite IDs": "شناسه‌های علاقه",
    "Favorites": "علاقه‌مندی‌ها",
    "Features": "ویژگی‌ها",
    "Field backgrounds and button text": "پس‌زمینه‌های فیلد و متن دکمه",
    "Field borders and buttons.": "حاشیه‌های فیلد و دکمه‌ها.",
    "Field of view": "میدان دید",
    "Field text": "متن فیلد",
    "File Upload": "آپلود فایل",
    "File Upload Button": "دکمه آپلود فایل",
    "Find playlist elements": "پیدا کردن عناصر لیست پخش",
    "Find this in your Bunny Stream dashboard under API.": "این را در داشبورد Bunny Stream خود تحت API پیدا کنید.",
    "Find this in your Bunny Stream dashboard under Security settings.": "این را در داشبورد Bunny Stream خود تحت تنظیمات امنیتی پیدا کنید.",
    "Finish": "پایان",
    "First day of week": "اولین روز هفته",
    "First time slot in timeline views (e.g., 06:00:00)": "اولین شکاف زمانی در نمایش‌های خط زمانی (به عنوان مثال، 06:00:00)",
    "Fixed slide width": "عرض اسلاید ثابت",
    "Flick power": "قدرت فلیک",
    "Flip": "تراشه",
    "Flip horizontal": "تراشه افقی",
    "Flip vertical": "تراشه عمودی",
    "Floating effect": "اثر شناور",
    "Focus shadow color": "رنگ سایه تمرکز",
    "Focus shadow width": "عرض سایه تمرکز",
    "Focus the first focusable element": "تمرکز بر روی اولین عنصر قابل تمرکز",
    "Follow cursor": "دنبال مکان‌نما",
    "Follow the steps below to license the plugin:": "برای مجوز افزونه مراحل زیر را دنبال کنید:",
    "Footer A": "پاورقی الف",
    "Footer B": "پاورقی ب",
    "Footer C": "پاورقی ج",
    "For browsers not supporting fullscreen": "برای مرورگرهایی که از تمام صفحه پشتیبانی نمی‌کنند",
    "For changing the border radius": "برای تغییر شعاع حاشیه",
    "For token protected videos": "برای ویدیوهای محافظت شده با توکن",
    "For use with sliders that move 1 slide at a time": "برای استفاده با اسلایدرهایی که 1 اسلاید را در یک بار حرکت می‌دهند",
    "For use with the popover/tooltip element (enable Dynamic tooltip text)": "برای استفاده با عنصر popover/tooltip (فعال‌سازی متن نکته ابزار پویا)",
    "For use with vertical sliders": "برای استفاده با اسلایدرهای عمودی",
    "Force exit fullscreen then allow": "اجبار خروج از تمام صفحه سپس اجازه دهید",
    "Force images to be 100% slide height": "اجبار تصاویر برای 100% ارتفاع اسلاید",
    "Force images to be 100% slide width": "اجبار تصاویر برای 100% عرض اسلاید",
    "Force window resize when opened": "اجبار تغییر اندازه پنجره هنگام باز",
    "Form reset": "بازنشانی فرم",
    "Form wide colors": "رنگ‌های گسترده فرم",
    "Forward": "جلو",
    "Free scrolling": "لغزش آزاد",
    "Frequency": "فرکانس",
    "Friday": "جمعه",
    "From bottom of player when controls visible": "از پایین پخش‌کننده هنگامی که کنترل‌ها نمایان هستند",
    "Full width": "عرض کامل",
    "Full width content": "محتوای عرض کامل",
    "Full window": "پنجره کامل",
    "Full window for browsers not supporting fullscreen": "پنجره کامل برای مرورگرهایی که از تمام صفحه پشتیبانی نمی‌کنند",
    "Fullscreen": "تمام صفحه",
    "Gallery": "گالری",
    "Gallery mode": "حالت گالری",
    "Gap between label and checkbox": "شکاف بین برچسب و چک‌باکس",
    "Gap between stacked toasts (px)": "شکاف بین toast‌های انباشته شده (px)",
    "General colors": "رنگ‌های عمومی",
    "Generate Authentication Tokens": "تولید توکن‌های احراز هویت",
    "Generate Password Icon": "تولید نماد رمز عبور",
    "Geolocation Input": "ورودی موقعیت‌یابی",
    "Georadius": "شعاع جغرافیایی",
    "Gestures": "ژست‌ها",
    "Go back to previous scene": "برگشتن به صحنه قبلی",
    "Go to favorite": "رفتن به علاقه",
    "Grid Color": "رنگ شبکه",
    "Grid views": "نمایش‌های شبکه",
    "Group images into lightbox": "گروه‌بندی تصاویر در جعبه نور",
    "Grouping": "گروه‌بندی",
    "Grouping Scope": "دامنه گروه‌بندی",
    "Has active membership": "دارای عضویت فعال است",
    "Has active membership ID": "دارای شناسه عضویت فعال است",
    "Has active subscription": "دارای اشتراک فعال است",
    "Has active subscription ID": "دارای شناسه اشتراک فعال است",
    "Has child category": "دارای دسته‌بندی فرزند است",
    "Has custom excerpt": "دارای خلاصه سفارشی است",
    "Has post content": "دارای محتوای نوشته است",
    "Hash": "هش",
    "Hash link to close": "پیوند هش برای بستن",
}

def translate_po_file(input_file, output_file):
    """Translate a PO file from English to Persian."""
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Split into lines for processing
    lines = content.split('\n')
    result = []
    i = 0

    while i < len(lines):
        line = lines[i]

        # Check if this is a msgid line
        if line.startswith('msgid "'):
            msgid_line = line
            # Extract the msgid value
            msgid_match = re.match(r'msgid "(.*)"', line)
            if msgid_match:
                msgid_text = msgid_match.group(1)

                # Look for the translation
                result.append(msgid_line)
                i += 1

                # Process the msgstr line
                if i < len(lines) and lines[i].startswith('msgstr'):
                    # Get the translation or leave empty
                    if msgid_text in translations:
                        translated = translations[msgid_text]
                        result.append(f'msgstr "{translated}"')
                    else:
                        result.append(lines[i])  # Keep empty msgstr if no translation
                    i += 1
                else:
                    i += 1
            else:
                result.append(line)
                i += 1
        else:
            result.append(line)
            i += 1

    # Write the translated content
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(result))

    print(f"Translation completed: {output_file}")

if __name__ == "__main__":
    input_file = "bricksextras-fa_IR.po"
    output_file = "bricksextras-fa_IR.po"
    translate_po_file(input_file, output_file)
